name: Build Pansou
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20' # 建议用1.20，因为你之前报过sonic库的错
          cache: false
      - name: Build
        run: |
          cd pansou   # <--- 加上这一行，进入存放 go.mod 的目录
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -v -o pansou main.go
      - uses: actions/upload-artifact@v4
        with:
          name: pansou-linux
          path: pansou/pansou # <--- 注意路径也要改为 pansou/pansou
